/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReserverRouteImport } from './routes/reserver'
import { Route as ObjetsRouteImport } from './routes/objets'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as CreationsRouteImport } from './routes/creations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as CadeauRouteImport } from './routes/cadeau'
import { Route as BrunchRouteImport } from './routes/brunch'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ReserverRoute = ReserverRouteImport.update({
  id: '/reserver',
  path: '/reserver',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjetsRoute = ObjetsRouteImport.update({
  id: '/objets',
  path: '/objets',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const CreationsRoute = CreationsRouteImport.update({
  id: '/creations',
  path: '/creations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const CadeauRoute = CadeauRouteImport.update({
  id: '/cadeau',
  path: '/cadeau',
  getParentRoute: () => rootRouteImport,
} as any)
const BrunchRoute = BrunchRouteImport.update({
  id: '/brunch',
  path: '/brunch',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brunch': typeof BrunchRoute
  '/cadeau': typeof CadeauRoute
  '/carte': typeof CarteRoute
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRoute
  '/guide': typeof GuideRoute
  '/objets': typeof ObjetsRoute
  '/reserver': typeof ReserverRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brunch': typeof BrunchRoute
  '/cadeau': typeof CadeauRoute
  '/carte': typeof CarteRoute
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRoute
  '/guide': typeof GuideRoute
  '/objets': typeof ObjetsRoute
  '/reserver': typeof ReserverRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/brunch': typeof BrunchRoute
  '/cadeau': typeof CadeauRoute
  '/carte': typeof CarteRoute
  '/contact': typeof ContactRoute
  '/creations': typeof CreationsRoute
  '/guide': typeof GuideRoute
  '/objets': typeof ObjetsRoute
  '/reserver': typeof ReserverRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/brunch'
    | '/cadeau'
    | '/carte'
    | '/contact'
    | '/creations'
    | '/guide'
    | '/objets'
    | '/reserver'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/brunch'
    | '/cadeau'
    | '/carte'
    | '/contact'
    | '/creations'
    | '/guide'
    | '/objets'
    | '/reserver'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/brunch'
    | '/cadeau'
    | '/carte'
    | '/contact'
    | '/creations'
    | '/guide'
    | '/objets'
    | '/reserver'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BrunchRoute: typeof BrunchRoute
  CadeauRoute: typeof CadeauRoute
  CarteRoute: typeof CarteRoute
  ContactRoute: typeof ContactRoute
  CreationsRoute: typeof CreationsRoute
  GuideRoute: typeof GuideRoute
  ObjetsRoute: typeof ObjetsRoute
  ReserverRoute: typeof ReserverRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reserver': {
      id: '/reserver'
      path: '/reserver'
      fullPath: '/reserver'
      preLoaderRoute: typeof ReserverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objets': {
      id: '/objets'
      path: '/objets'
      fullPath: '/objets'
      preLoaderRoute: typeof ObjetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creations': {
      id: '/creations'
      path: '/creations'
      fullPath: '/creations'
      preLoaderRoute: typeof CreationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadeau': {
      id: '/cadeau'
      path: '/cadeau'
      fullPath: '/cadeau'
      preLoaderRoute: typeof CadeauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brunch': {
      id: '/brunch'
      path: '/brunch'
      fullPath: '/brunch'
      preLoaderRoute: typeof BrunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BrunchRoute: BrunchRoute,
  CadeauRoute: CadeauRoute,
  CarteRoute: CarteRoute,
  ContactRoute: ContactRoute,
  CreationsRoute: CreationsRoute,
  GuideRoute: GuideRoute,
  ObjetsRoute: ObjetsRoute,
  ReserverRoute: ReserverRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
